### PR TITLE
Do not pass the port if it is not in the URI

### LINKED ISSUE #675: `PGPORT` environment variable doesn't seem to be respected in v1.3.0
Hi there guys, wanted to alert you to an issue that I started facing starting after the v1.3.0 release on Friday. I use sqitch via the docker image & the recommended script as documented in the README and docker hub. I am not sure if this an issue with the v1.3.0 release in general or just the docker setup. I'm also not sure if it's all `PG*` environment variables or just `PGPORT`. Basically, the behavior I'm seeing is that even though `PGPORT` is in the environment, when trying to run migrations I get an error like this:
```
Adding registry tables to pg-localdev
psql: error: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 5432?
could not connect to server: Connection refused
        Is the server running on host "localhost" (127.0.0.1) and accepting
        TCP/IP connections on port 5432?
"psql" unexpectedly returned exit value 2
```
Steps to reproduce:
1. Have a postgres instance running on port 5433
2. Download the `sqitch` docker running script from the README of this repo
3. Try to run some migrations with `PGPORT=5433` in the environment

This is what my sqitch config file looks like:
```
[core]
  engine = pg
  top_dir = db/
[engine "pg"]
  target = pg-localdev
[target "pg-localdev"]
  uri = db:postgresql://postgres:password@localhost/database
```

I was able to solve this issue for myself by just pinning the tag in the `sqitch` runner script to `v1.2.1.1` (side note: `v1.2.1` is listed as a supported tag on docker hub but doesn't seem to work: https://hub.docker.com/r/sqitch/sqitch/ ; I had to come look at the tags in the repo to find that you use a versioning scheme w/ 4 components instead of 3). So I'm not blocked here or anything, just thought you guys might want a heads up as this caused some github actions to start failing for me; I am using their "port mapping" functionality (https://docs.github.com/en/actions/using-containerized-services/about-service-containers) and was specifying the port with `PGPORT`, and my tests suddenly started failing. I'm guessing the same might be true for some others as well.

### PR DESCRIPTION
**Pull request by theory**
Otherwise PGPORT is overridden! Fixes #675.

### CODE REVIEW

File: Changes [hunk 1]
```diff
@@ -2,6 +2,10 @@ Revision history for Perl extension App::Sqitch
 
 1.3.1
 
+     - Fixed a bug introduced in v1.3.0 where the Postgres engine would ignore
```
Comment (autarch) [inline Changes:5]: "ignore always". I think you just mean "always.

File: lib/App/Sqitch/Engine/pg.pm [hunk 2]
```diff
@@ -61,7 +61,7 @@ has _psql => (
             [ user   => $self->username ],
             [ dbname => $uri->dbname    ],
             [ host   => $uri->host      ],
-            [ port   => $uri->port      ],
+            [ port   => $uri->_port      ],
```
Comment (autarch) [inline lib/App/Sqitch/Engine/pg.pm:64]: It might be worth adding a comment that `_port` is in fact the documented way to get a port-sans-default from a `URI` (gross API).

**Review by autarch — CHANGES_REQUESTED** [review]
Looks good except for some small issues.

File: lib/App/Sqitch/Engine/pg.pm (hunk 2 above)
Comment (theory) [reply lib/App/Sqitch/Engine/pg.pm]: Good idea, avoid the issue in the future (hopefully). Done in 8f72ee6a.

**Review by autarch — APPROVED** [review]
